<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBn2G77q\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBn2G77q/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBn2G77q.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBn2G77q\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerBn2G77q\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'Bn2G77q',
    'container.build_id' => '33e77867',
    'container.build_time' => 1539496711,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBn2G77q');
